version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.GT_DEPENDABOT_PAT }}
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    target-branch: "development"
    open-pull-requests-limit: 10
    versioning-strategy: "lockfile-only"
    registries:
      - github

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    target-branch: "development"
    open-pull-requests-limit: 10
    registries:
      - github

  # Enable version updates for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "development"
    open-pull-requests-limit: 10
    registries:
      - github
  
