---
name: main push workflow

on:
  workflow_call:
  push:
    branches:
      - master

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: write  

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    permissions: read-all
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-setup.yaml@v1

  lint:
    name: Lint Code Base
    needs: [setup]
    permissions:
      contents: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: Super linter
        uses: GigaTech-net/public-reusable-workflows/.github/actions/super-linter@v1
        with:
          env_file_path: .github/super-linter-push.env

  secret-scan:
    name: Secret Scan
    needs: [setup]
    permissions: read-all
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-secret-scan.yaml@v1

  spellcheck:
    name: Spellcheck codebase
    needs: [setup]
    permissions:
      contents: write
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-spellcheck.yaml@v1

  tag:
    needs: [setup, lint, secret-scan, spellcheck]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Setup GitHub token
        uses: GigaTech-net/public-reusable-workflows/.github/actions/setup-token@v1
        with:
          app_id: ${{ secrets.KEYROTATION_APPID_GT_GH }}
          private_key: ${{ secrets.KEYROTATION_PVTKEY_GT_GH }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.70.0 # Don't use @main or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true